# Back-office, production Dockerfile
FROM node:alpine3.22 AS build-stage

LABEL \
    com.meetmeat.project="backoffice" \
    com.meetmeat.env="production"

WORKDIR /app
COPY backoffice/package*.json ./
RUN npm install
COPY /backoffice .
RUN npm run build

# production stage
FROM nginx:alpine3.22 AS production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]