# Back-office, development Dockerfile
FROM node:lts-alpine

LABEL \
    com.meetmeat.project="backoffice" \
    com.meetmeat.env="dev"

RUN apk add --no-cache tzdata

WORKDIR /app

COPY backoffice/package*.json ./
RUN npm ci && npm cache clean --force


EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
